import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Providers";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import Particle from "@/components/Particle";

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-primary relative dark:bg-gray-900 bg-indigo-100">
        <Providers>
          <Particle />
          <Toaster />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
